project:
  type: website
  output-dir: docs

website:
  title: "Danielle Navarro"
  site-url: https://code.djnavarro.net
  repo-url: https://github.com/djnavarro/code
  open-graph: true
  search: false
  twitter-card:
    creator: "@djnavarro"
    card-style: summary_large_image
  navbar:
    title: false
    right:
      - text: Sites
        menu:
          - text: Homepage
            href: https://djnavarro.net
          - text: Data science blog
            href: https://blog.djnavarro.net
          - text: Computational art
            href: https://art.djnavarro.net
          - text: Coding projects
            href: https://code.djnavarro.net
          - text: Academic papers
            href: https://papers.djnavarro.net
          - text: More...
            href: https://djnavarro.net/sites/
  page-footer:
    center:
      - href: https://code.djnavarro.net
        text: code.djnavarro.net

format:
  html:
    highlight-style: atom-one    
    respect-user-color-scheme: true
    theme: 
      dark: blackpink.scss
      light: paleblue.scss
    css: styles.css
    include-after-body: plausible.html



